### ISSUE TITLE
install a' plugin version incompatibility

### ISSUE THREAD

**Issue by huhouhua** [Nestsiarenka/helm-template-preview-and-more#10]
![image](https://github.com/Nestsiarenka/helm-template-preview-and-more/assets/40319281/6f39ada0-5d29-48dd-93a8-52ee73b795e9)

**Comment by Nestsiarenka** [comment]
Hello. As I understand version of Visual Studio Code you use is 1.76.2. But the extension supports version 1.80.0 and higher. 

Could you please update Visual Studio Code to the newest version?

Meanwhile I will try to make the extension compatible with the version 1.76.2, in case if it's not possible for some reason to update Visual Studio Code.

**Comment by Nestsiarenka** [comment]
Ok, looks like I did it. Please, try to install the version 1.2.1. It should be compatible with your VS code version

**Comment by huhouhua** [comment]
OK, I'll try again

**Comment by huhouhua** [comment]
> Ok, looks like I did it. Please, try to install the version 1.2.1. It should be compatible with your VS code version

OK, I'll try again

**Comment by huhouhua** [comment]
> Ok, looks like I did it. Please, try to install the version 1.2.1. It should be compatible with your VS code version

Thank you, installation success!

**Comment by Nestsiarenka** [comment]
Thank you for your feedback! If you have any other issues or suggestion you are more than welcome!
