### ISSUE TITLE
directory structure not found,  the value.yaml file not found `The open file is not a Helm template`

### ISSUE THREAD

**Issue by huhouhua** [Nestsiarenka/helm-template-preview-and-more#11]
![image](https://github.com/Nestsiarenka/helm-template-preview-and-more/assets/40319281/e325cb76-a655-48b3-96b6-7e675891d73a)

**Comment by huhouhua** [comment]
Occurs version is `1.2.1`

**Comment by Nestsiarenka** [comment]
Hello. I can reproduce the issue and already working on a fix. I think I'll be able to publish fixed version today/tomorrow

**Comment by huhouhua** [comment]
> Hello. I can reproduce the issue and already working on a fix. I think I'll be able to publish fixed version today/tomorrow

Ok great!

**Comment by Nestsiarenka** [comment]
I have just posted `1.2.2`. Could you please give it a shot?

**Comment by huhouhua** [comment]
> I have just posted `1.2.2`. Could you please give it a shot?

okay

**Comment by MaxLevs** [comment]
I have this issue too
